---
title: "Buying a house in the US"
author: "Sunit Jain"
date: "August 12, 2015"
output:
  html_document:
    dev: svg
    toc: yes
    toc_depth: 3
---

```{r dependencies, eval=FALSE, results='hide',  echo=FALSE}
package = function(p) {
  if (!p %in% installed.packages()){ 
  		install.packages(p, dep=T)
  }
}

package("ggplot2")
package("knitr")
package("dplyr")
package("tidyr")
package("readr")
package("lubridate")
```

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
											echo=FALSE, warning=FALSE, message=FALSE)
```
## Data
This data set was downloaded from [Zillow](`http://www.zillow.com/research/data/`) on August 12, 2015. Direct links:

- [Zip](http://files.zillowstatic.com/research/public/Zip.zip)
- [Neighborhood](http://files.zillowstatic.com/research/public/Neighborhood.zip)
- [City](http://files.zillowstatic.com/research/public/City.zip)

```{r setup}
workdir=getwd()
datadir=paste(workdir, "data", sep="/")
zipdir=paste(datadir, "Zip", sep="/")
neighbordir=paste(datadir, "Neighborhood", sep="/")
citydir=paste(datadir, "City", sep="/")
dir.create(file.path(workdir, "figures"), showWarnings = FALSE)
```

# Zip

## Homes increasing values year over year.
```{r zip}
library(readr)
library(dplyr)
library(lubridate)
zip.inc.val=read_csv(paste(zipdir,"Zip_PctOfHomesIncreasingInValues_AllHomes.csv",sep="/"), col_names = T) %>% filter(Metro == "Ann Arbor")
```

```{r zip_plot}
library(tidyr)
zip.inc.val.long=zip.inc.val %>% 
    gather(Year,Percent,matches("-")) 
zip.inc.val.long$RegionName=as.factor(zip.inc.val.long$RegionName)
zip.inc.val.long$Year=ymd(zip.inc.val.long$Year, truncated=1)

library(ggplot2)
ggplot(na.omit(zip.inc.val.long), aes(Year,Percent,color=RegionName)) +
    geom_line(aes(group=RegionName)) +
    ggtitle("Percent of Homes Increasing In Values") +
    theme_minimal()
```

```{r interactive_zip_plot, results='as.is', comment=NA,cache=FALSE}
library(rCharts)
library(knitr)
i.plot=nPlot(
    Percent ~ Year,
    data = zip.inc.val.long,
    group= "RegionName",
    type = "lineChart"
)
i.plot$xAxis(axisLabel = "Year")
i.plot$yAxis(axisLabel = "Percent Increase", width=40)

i.plot$chart(tooltipContent = "#! function(key, x, y){
        return '<h3>' + key + '</h3>' + 
        '<p>' + y + ' in ' + x + '</p>'
        } !#")
#i.plot$show('inline', include_assets = TRUE, cdn = TRUE)
i.plot$save('figures/Figure_1_1.html', standalone = TRUE)
```
<iframe src ='figures/Figure_1_1.html', width = "860px", height = "450px"></iframe>
