---
title: "Place I’ve been"
author: "Sunit Jain"
date: "July 14, 2015"
output:
    html_document:
        toc: yes
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.height = (33.1)/6,
                      fig.width = (46.8)/6,
                      fig.retina = 4,
                      fig.path = "Figs",
                      echo=FALSE,
                      warning=FALSE,
                      message=FALSE)
```

```{r install, eval=FALSE}
install.packages("leaflet",dep=T)
```

```{r setup}
library(leaflet)
library(dplyr)
library(maps)

workdir="/Users/sunitj/GitHub/sandbox/Places"
setwd(workdir)
```

## United States
```{r states}
been.us=c("michigan", "california", "texas", "florida","new york", "illinois", "nevada")
mapStates = map("state", been.us,fill = TRUE, plot = FALSE)
leaflet(mapStates) %>%
    addTiles() %>%
    addPolygons(fill=T, color="blue",stroke = F) %>%
    addProviderTiles("CartoDB.Positron")
```

## World
```{r world}
been.world=c("usa", "india", "indonesia", "uae")
mapWorld=map("world", been.world, fill = T, plot = F)
leaflet(mapWorld) %>%
    addTiles() %>%
    addPolygons(fill=T, color="red", stroke = F) %>%
    addProviderTiles("CartoDB.Positron")
```




