---
title: "Time Report 2015"
author: "Sunit Jain"
output: pdf_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r dependencies}
package = function(p) {
	if (!p %in% installed.packages()){ install.packages(p) }
	require(p, character.only=TRUE)
}
package("data.table")
package("googlesheets")
package("dplyr")
package("ggplot2")
package("RColorBrewer")
package("xkcd")
package("extrafont")
package("lubridate")
package("magrittr")
package("knitr")
```

```{r move}
subDir=paste(month(now(), label=T, abbr = F), year(now()), sep="_")
monthDir=paste(getwd(),"data", subDir, sep="/")
dir.create(path = monthDir, recursive = T, showWarnings = FALSE)
```

```{r authenticate, eval=TRUE}
library(googlesheets)
ts.url="https://docs.google.com/a/umich.edu/spreadsheets/d/1ajQKLvYJOcK0wHOsfI8bfCcJmMAxpLfz1d65H3dY0Cg/edit?usp=sharing"
ts=gs_url(ts.url,lookup=T,visibility = "private")
```

```{r extract}
library(dplyr)
library(tidyr)
ytd=ts %>%
	gs_read(ws="2015", range="A2:BD24",verbose=T) %>%
	replace(is.na(.), 0) %>%
	filter(Total.Hrs.Spent != 0) %>%
	gather("Weeks","Hours", 5:56)
ytd$PI=as.factor(ytd$PI)
ytd$Projects=as.factor(ytd$Projects)

weeks.2015=ts %>%
	gs_read(ws="2015 Weeks",verbose=T)
```

```{r beautify, eval=FALSE}
library(xkcd)
library(extrafont)
download.file("http://simonsoftware.se/other/xkcd.ttf", dest="xkcd.ttf", mode="wb")
system("mkdir ~/.fonts")
system("cp xkcd.ttf ~/.fonts")
font_import(pattern="[X|x]kcd", prompt=F)
loadfonts()
```

This is a work distribution and time report for the month of ``r month(now(), label=T, abbr = F)``. The report was generated on: `r Sys.Date()`.

## Last Month
The following is the work distribution for the last month

```{r monthly}
library(ggplot2)
library(RColorBrewer)
weeks.this.month=weeks.2015[weeks.2015$Month == paste(month(now(), label=T, abbr = F), "2015", sep = " "), ]
this.month=paste("Week",
								 (
								 	weeks.this.month$X2015.Cum.Weeks - weeks.this.month$X2015.Weeks +1
								 	) : weeks.this.month$X2015.Cum.Weeks,
								 sep = ".")
mtd=ytd %>%
	select(PI,Weeks,Hours) %>%
	filter(Weeks %in% this.month) %>%
	group_by(PI,Weeks) %>%
	summarise(PI.Hours=sum(Hours))

# plot
ggplot(mtd,aes(Weeks, PI.Hours))+
	geom_area(aes(group=PI, fill=PI), position="stack", color="black") + 
	guides(fill=guide_legend(override.aes=list(colour=NA))) +
	scale_fill_brewer(palette = "Set1") +
	scale_color_brewer(palette = "Set1") +
	geom_hline(aes(yintercept=40), linetype=2) +
	ggtitle(paste(month(now(), label=T, abbr = F), "2015")) +
	theme(axis.text.x = element_text(angle = 90),
				plot.title=element_text(vjust = 1)) +
	theme_xkcd()
ggsave(filename = "data/monthly-1.pdf")
embed_fonts("data/monthly-1.pdf")
```

```{r monthByPI, eval=FALSE}
mpi=mtd %>%
	select(PI,PI.Hours) %>%
	group_by(PI) %>% 
	summarise(m.PI.Hours=sum(PI.Hours))

# plot
library(scales)
ggplot(mpi, aes(x=1, y=m.PI.Hours, fill=PI)) +
        ggtitle("How I've spent my hours this month") +
        geom_bar(stat="identity", color='black') +
        guides(fill=guide_legend(override.aes=list(colour=NA))) +
				coord_flip() +
				theme_xkcd() +
        theme(axis.ticks=element_blank(),  # the axis ticks
              axis.title=element_blank(),  # the axis labels
              axis.text.y=element_blank(), # the 0.75, 1.00, 1.25 labels
              axis.text.x=element_text(color='black', size = 12, angle = 90, family = "Comic Sans MS")
        			) +
				scale_y_continuous(
        	    breaks=cumsum(mpi$m.PI.Hours) - mpi$m.PI.Hours/2,
          	  labels=percent(mpi$m.PI.Hours/sum(mpi$m.PI.Hours)),
        	    position_dodge(height = 1)
        ) +
				scale_fill_brewer(palette = "Set1")
```

## Year to date
```{r byPI}
pi.ytd=ytd %>%
	select(PI,Weeks,Hours) %>%
	group_by(PI,Weeks) %>%
	summarise(PI.Hours=sum(Hours))

# plot
ggplot(pi.ytd,aes(Weeks, PI.Hours))+
	geom_area(aes(group=PI, fill=PI), position="stack", color="black") +
	guides(fill=guide_legend(override.aes=list(colour=NA))) +
	scale_fill_brewer(palette = "Set1") +
	scale_color_brewer(palette = "Set1") +
	geom_hline(aes(yintercept=40), linetype=2) +
	ggtitle("Year to date")+
	theme_xkcd() +
	theme(axis.text.x = element_text(angle = 90),
				plot.title= element_text(vjust=1))
ggsave(filename = "data/byPI-1.pdf")
embed_fonts("data/byPI-1.pdf")
```

```{r copyFiles, results="hide"}
files=list.files(path=paste(getwd(),"data", sep="/"), pattern = "*.pdf", full.names = T)
file.copy(from=files,to=monthDir)
file.remove(files)
```

\newpage

# Income

```{r contacts}
contacts=ts %>%
	gs_read(ws="Contacts",verbose=T) %>%
	replace(is.na(.), "")
#contacts$Abb=as.factor(contacts$Abb)
```

```{r balance_sheet}
bs=ts %>%
	gs_read(ws="BalanceSheet",verbose=T) %>%
	replace(is.na(.), "000000")
#bs$Abb=as.factor(bs$Abb)
bs$Date=mdy(bs$Date)
bs$Period.From=mdy(bs$Period.From)
bs$Period.To=mdy(bs$Period.To)
```

```{r who_do_i_bill}
# get_all_PIs whose project is still ongoing
all.PIs=contacts %>% filter(Status == "Ongoing"| Status == "Ending")
# check when they were last billed
last.billed=bs %>% group_by(Abb) %>% arrange(desc(Period.To)) %>% distinct(Abb) %>% select(-PI)

# get new billing cycle
this.billing.cycle=left_join(all.PIs,last.billed, by="Abb") %>% select(Abb, PI, Invoice.Num, Date, Type, Period.From, Period.To, Shortcode, Rate, Status)
this.billing.cycle$Period.From=ceiling_date(this.billing.cycle$Period.To, "week") + days(1)
this.billing.cycle$Period.To= ceiling_date(now(), "week")
this.billing.cycle$Date=today()
this.billing.cycle$Week.From=week(this.billing.cycle$Period.From)
this.billing.cycle$Week.To=week(this.billing.cycle$Period.To)
```

```{r pi_last_cycle}
# Get hours worked per PI this since last billed
get_billing_hours=function(x) {
	Week.From=x$Week.From
	Week.To=x$Week.To
	worked.for=x$PI
	x$Invoice.Num=paste(x$Abb,
											paste("00",
														as.numeric(strsplit(x$Invoice.Num, split = "-")[[1]][2]) + 1,
														sep = ""),
											sep = "-")
	weeks.worked=paste("Week",
				Week.From : Week.To,
				sep = ".")
	x$Hours=as.numeric(ytd %>%
										 	select(PI,Weeks,Hours) %>%
										 	filter(PI == worked.for) %>%
										 	filter(Weeks %in% weeks.worked) %>%
										 	summarise(PI.Hours=sum(Hours))
										 	)
	#return(data.frame("Abb"=x$Abb,"B.Hours"=pi.hr,"Invoice.Num"=pi.invoice))
	return(x)
	}

library(data.table)
this.billing.cycle=this.billing.cycle %>% 
	rowwise() %>% 
	do(values=get_billing_hours(.)) %$% values %>%
	rbindlist() %>%
	mutate(Total=Hours*Rate) %>% 
	select(-c(Week.To,Week.From))

```

```{r filter_projects_by_hours}
# reorder columns accoding to the sheet
setcolorder(this.billing.cycle,c("Abb", "PI", "Invoice.Num", "Date", "Type", "Period.From", "Period.To", "Shortcode", "Hours", "Rate", "Total", "Status"))
# don't bill unless number of hours worked is greater that or equal to 5 OR the project is ending.
ongoing=this.billing.cycle %>% filter(Status == "Ongoing") %>% filter(Hours >= 5)
ending=this.billing.cycle %>% filter(Status == "Ending")
this.billing.cycle=rbind(ongoing,ending)
this.billing.cycle %>% select(-c(Abb,Type)) %>% kable(.)
```

```{r update_balance_sheet}
for (i in 1:nrow(this.billing.cycle)){
	gs_add_row(ss=ts, ws="BalanceSheet", input=this.billing.cycle[i,], verbose=TRUE)
	Sys.sleep(0.3)
}
```

\newpage
```{r sessionInfo, eval=FALSE}
sessionInfo()
```

